name: LWR Project CI
on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev

permissions:
    actions: write
    contents: read

jobs:
    continuous_integration:
        name: ⬣ Continuous Integration
        runs-on: ubuntu-latest
        env:
            SESSION_SECRET: 'super-long-secret-for-the_github_action-session'
            ACCESS_TOKEN_SECRET: 'github_actions-access-token-secret'
            REFRESH_TOKEN_SECRET: 'github_actions-refresh-token-secret'
        steps:
            - name: ⬇️ Checkout repo
              uses: actions/checkout@v3

            - name: ⎔ Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: true

            - name: 🔬 Lint
              run: yarn lint

            - name: ✅ Unit tests
              run: yarn test
